spring:
  application:
    name: alertmanager
  data:
    mongodb:
      uri: mongodb://localhost:27017/alertmanager
server:
  port: 8081
#告警相关表明配置
alertmanager:
#告警记录表明
  alertrecord:
    tablename: alertRecord
  #告警字典表名
  alertdictionary:
    tablename: alertDictionary
  #通知白名单表名
  alertexcluse:
    tablename: alertExcluse
  #消息重发间隔时长单位为s:秒，m:分，h:时，d：天
  resendinterval: 30m
  #ES主机和端口配置
  elasticsearch:
  #ES的主机端口配置，支持多台主机,
    hostnames: ['localhost:9200']
    #索引的时间格式
    datepattern: yyyyMM
    #es的类型
    type: HISTORY
    #index的前缀
    indexpre: alert-
    #模板文件地址，根据ES版本设置
    template: "classpath:notifysend/esmapping5.x.json"
  #notifyService endpoint
  notifyurl: http://10.138.16.192:8888/api/notify/message?async=1
  code:
    alertlevel:
      error: 紧急
      warn: 严重
      info: 一般
      debug: 提示
    #告警分类
    alertCategory:
      machine: 机器
      app: 应用
    #告警类型
    alertType:
      cockpit_schedule_task_exit: 容器实例退出
      mysql_status_handlers_read_rnd: mysql索引不合理
      service_down: 服务不可用
      node_reboot: 系统重启
      node_cpu_pct_threshold_exceeded: 节点CPU使用率过高
      node_mem_threshold_exceeded: 节点剩余内存不足
      node_mem_pct_threshold_exceeded: 节点内存使用率过高
      node_fs_pct_threshold_exceeded: 节点文件系统使用率过高
      node_tcp_conn_toomuch: 节点TCP连接数过高
      node_disk_io_util_threshold_exceeded: 节点磁盘IO过高
      redis_service_down: redis服务不可用
      redis_mem_pct_threshold_exceeded: Redis内存使用率过高
      redis_mem_threshold_exceeded: Redis内存不足
      redis_toomany_command_executed: Redis命令执行频繁
      redis_dangerous_command_executed: Redis执行危险命令
