spring:
  application:
    name: alertmanager
  data:
    mongodb:
      uri: mongodb://10.138.40.221:27018/alert
server:
  port: 8080
#告警相关表明配置
alertmanager:
#告警记录表明
  alertrecord:
    tablename: alertRecord
  #告警字典表名
  alertdictionary:
    tablename: alertDictionary
  #通知白名单表名
  alertexcluse:
    tablename: alertExcluse
  #消息重发间隔时长单位为s:秒，m:分，h:时，d：天
  resendinterval: 3d
  #ES主机和端口配置
  elasticsearch:
  #ES的主机端口配置，支持多台主机,
    hostnames: ['10.138.16.188:9200','10.138.16.189:9200','10.138.16.190:9200']
    #索引的时间格式
    datepattern: yyyyMM
    #es的类型
    type: HISTORY
    #index的前缀
    indexpre: alert-
    #模板文件地址，根据ES版本设置
    template: "classpath:notifysend/esmapping5.x.json"
  #notifyService endpoin
  notifyurl: http://10.138.16.192:8888/api/notify/message?async=1
  code:
    alertlevel:
      critical: 紧急
      serious: 严重
      warning: 一般
      info: 提示
    #告警分类
    alertCategory:
      machine: 机器
      app: 应用
    #告警类型
    alertType:
      host_service_down: 机器监控数据无法获取
      host_reboot: 机器重启
      host_cpu_pct_high: CPU利用率过高
      host_mem_pct_high: 内存利用率过高
      host_mem_available_low: 机器内存剩余量不足
      host_fs_pct_high: 文件系统利用率过高
      host_tcp_conn_toomuch: TCP连接数过多
      host_disk_ioutil_pct_high: 磁盘io利用率过高
      app_crash: 应用服务宕机
      http_requests_delay_high: 应用服务访问响应慢
      http_errors_rate_high: 应用服务错误率高
      dubbo_requests_delay_high: dubbo服务响应慢
      dubbo_errors_rate_high: dubbo服务错误率高
    alertType1:
      cockpit_schedule_task_exit: 容器实例退出
      mysql_status_handlers_read_rnd: mysql索引不合理
      service_down: 服务不可用
      node_reboot: 系统重启
      node_cpu_pct_threshold_exceeded: 节点CPU使用率过高
      node_mem_threshold_exceeded: 节点剩余内存不足
      node_mem_pct_threshold_exceeded: 节点内存使用率过高
      node_fs_pct_threshold_exceeded: 节点文件系统使用率过高
      node_tcp_conn_toomuch: 节点TCP连接数过高
      node_disk_io_util_threshold_exceeded: 节点磁盘IO过高
      redis_service_down: redis服务不可用
      redis_mem_pct_threshold_exceeded: Redis内存使用率过高
      redis_mem_threshold_exceeded: Redis内存不足
      redis_toomany_command_executed: Redis命令执行频繁
      redis_dangerous_command_executed: Redis执行危险命令

